export type Quarter = {
  statement_type?: string;
  source_provider?: string | null;
  source_timestamp?: string | null;
  fetched_at?: string;
  revenue_qoq?: number | null;
  pat_qoq?: number | null;
  ebitda_qoq?: number | null;
  margin_qoq_bps?: number | null;
  margin_yoy_bps?: number | null;
  total_income?: number | null;
  net_interest_income?: number | null;
  operating_profit?: number | null;
  aum?: number | null;
  gnpa?: number | null;
  nnpa?: number | null;
  financial_year: number;
  quarter: number;
  label: string;
  revenue: number | null;
  ebitda: number | null;
  pat: number | null;
  eps: number | null;
  debt: number | null;
  cfo: number | null;
  roe: number | null;
  roce: number | null;
  revenue_yoy: number | null;
  pat_yoy: number | null;
  ebitda_yoy: number | null;
  margin: number | null;
  source_url: string;
  revision: number;
  verification_status: string;
};
export type Company = {
  subscription_history?: {
    date: string;
    exchange: string;
    category: string;
    multiple: number | null;
    subscription_pct: number | null;
    bid_shares: number | null;
    offered_shares: number | null;
  }[];
  company_type?: string;
  lifecycle?: string;
  gmp_estimated_price?: number | null;
  annuals?: (Partial<Quarter> & { financial_year: number })[];
  subscription?: {
    observed_at: string;
    source_provider: string | null;
    source_url: string | null;
    categories: Record<string, { multiple: string | null }> | null;
    multiple: number | null;
  } | null;
  applicant_guide: ApplicantGuide | null;
  id: string;
  ipo_id: string;
  slug: string;
  name: string;
  sector: string;
  board: string;
  is_demo: boolean;
  ticker: string | null;
  exchange: string | null;
  status: string;
  quality: string;
  open_date: string | null;
  close_date: string | null;
  listing_date: string | null;
  listing_fy: number | null;
  listing_quarter: number | null;
  price_low: number | null;
  price_high: number | null;
  issue_price: number | null;
  listing_price: number | null;
  lot_size: number | null;
  minimum_application: number | null;
  issue_size: number | null;
  fresh_issue: number | null;
  ofs: number | null;
  gmp: number | null;
  gmp_percent: number | null;
  gmp_timestamp: string | null;
  gmp_quality: string;
  cmp: number | null;
  price_date: string | null;
  ath: number | null;
  high_52w: number | null;
  low_52w: number | null;
  return_ipo: number | null;
  return_listing: number | null;
  drawdown: number | null;
  latest: Partial<Quarter>;
  quarters: Quarter[];
  trend: { state: string; score: number | null; reason: string; version: string };
  business_vs_price: string;
  valuation: {
    pe: number | null;
    market_cap: number | null;
    peer_median_pe: number | null;
    ev_ebitda: number | null;
  } | null;
  valuation_label: string;
  screener_url: string | null;
  exchange_url: string | null;
  baseline?: Partial<Quarter> & { pe: number | null; market_cap: number | null };
  documents?: { kind: string; url: string }[];
  sources?: {
    field_name: string;
    source_url: string;
    verification_status: string;
    fetched_at: string;
  }[];
  performance?: Record<string, number | null>;
};
export type ApplicantGuide = {
  category: string;
  min_lots: number | null;
  max_lots: number | null;
  max_amount: number | null;
  bid_deadline: string | null;
  mandate_deadline: string | null;
  allotment_date: string | null;
  unblock_date: string | null;
  schedule_status: 'TENTATIVE' | 'CONFIRMED';
  registrar_name: string | null;
  registrar_url: string | null;
  business_summary: string | null;
  strengths: string | null;
  risks: string | null;
  proceeds: string | null;
  source_url: string;
  reviewed_on: string;
  verification_status: string;
};
export type SiteMessage = {
  id: string;
  title: string;
  content: string;
  attribution: string | null;
  kind: 'quote' | 'message';
  enabled: boolean;
  active_from: string | null;
  active_to: string | null;
};
export type Advertisement = {
  id: string;
  text: string;
  image_url: string | null;
  destination_url: string;
  placement: string;
  enabled: boolean;
};
export type TrackerResult = {
  items: Company[];
  total: number;
  page: number;
  page_size: number;
  financial_years: number[];
  sectors: string[];
  demo: boolean;
  current_fy: number;
  current_quarter: number;
};
