"""market_data_scheduler"""

import sqlalchemy as sa
from alembic import op

revision = "626a25f2c463"
down_revision = "20260920_applicant_guides"
branch_labels = None
depends_on = None


def upgrade():
    op.create_index("ix_subscription_ipo_observed", "ipo_subscriptions", ["ipo_id", "observed_at"])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_raw_payloads",
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("data_type", sa.String(length=40), nullable=False),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("payload_text", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_raw_payloads_payload_hash"),
        "data_raw_payloads",
        ["payload_hash"],
        unique=False,
    )
    op.create_table(
        "job_locks",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "scheduler_controls",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "ingestion_job_errors",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("item", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["data_import_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_job_errors_run_id"), "ingestion_job_errors", ["run_id"], unique=False
    )
    with op.batch_alter_table(
        "annual_financials", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_constraint(
            (
                "annual_financials_company_id_financial_year_key"
                if op.get_bind().dialect.name == "postgresql"
                else "uq_annual_financials_company_id"
            ),
            type_="unique",
        )
        batch.add_column(sa.Column("revision", sa.Integer(), server_default="1", nullable=False))
        batch.add_column(sa.Column("source_url", sa.Text(), nullable=True))
        batch.add_column(
            sa.Column(
                "statement_type", sa.String(length=20), server_default="STANDALONE", nullable=False
            )
        )
        batch.add_column(sa.Column("period_start", sa.Date(), nullable=True))
        batch.add_column(sa.Column("period_end", sa.Date(), nullable=True))
        batch.add_column(sa.Column("source_provider", sa.String(length=100), nullable=True))
        batch.add_column(sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column("filing_id", sa.String(length=200), nullable=True))
        batch.add_column(sa.Column("raw_payload_id", sa.String(length=36), nullable=True))
        batch.add_column(sa.Column("payload_hash", sa.String(length=64), nullable=True))
        batch.add_column(sa.Column("parser_version", sa.String(length=40), nullable=True))
        batch.add_column(sa.Column("industry_metrics", sa.JSON(), nullable=True))
        batch.create_unique_constraint(
            "uq_annual_revision", ["company_id", "financial_year", "revision"]
        )
        batch.create_foreign_key(
            "fk_annual_financials_raw", "data_raw_payloads", ["raw_payload_id"], ["id"]
        )
    with op.batch_alter_table(
        "companies", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.add_column(
            sa.Column(
                "company_type", sa.String(length=20), server_default="GENERAL", nullable=False
            )
        )
        batch.add_column(sa.Column("isin", sa.String(length=12), nullable=True))
        batch.create_unique_constraint("uq_companies_isin", ["isin"])
    with op.batch_alter_table(
        "data_import_runs", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.add_column(sa.Column("job_name", sa.String(length=40), nullable=True))
        batch.add_column(sa.Column("trigger", sa.String(length=20), nullable=True))
        batch.add_column(sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column("counters", sa.JSON(), nullable=True))
        batch.add_column(sa.Column("parameters", sa.JSON(), nullable=True))
    op.create_index(
        op.f("ix_data_import_runs_job_name"), "data_import_runs", ["job_name"], unique=False
    )
    with op.batch_alter_table(
        "ipo_gmp_history", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.add_column(sa.Column("source_provider", sa.String(length=100), nullable=True))
        batch.add_column(sa.Column("raw_payload_id", sa.String(length=36), nullable=True))
        batch.create_foreign_key(
            "fk_ipo_gmp_history_raw", "data_raw_payloads", ["raw_payload_id"], ["id"]
        )
    with op.batch_alter_table(
        "ipo_subscriptions", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.add_column(sa.Column("categories", sa.JSON(), nullable=True))
        batch.add_column(sa.Column("source_provider", sa.String(length=100), nullable=True))
        batch.add_column(sa.Column("source_url", sa.Text(), nullable=True))
        batch.add_column(sa.Column("payload_hash", sa.String(length=64), nullable=True))
        batch.add_column(sa.Column("raw_payload_id", sa.String(length=36), nullable=True))
        batch.create_foreign_key(
            "fk_ipo_subscriptions_raw", "data_raw_payloads", ["raw_payload_id"], ["id"]
        )
    with op.batch_alter_table(
        "ipos", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.add_column(sa.Column("raw_status", sa.String(length=40), nullable=True))
        batch.add_column(sa.Column("lifecycle", sa.String(length=30), nullable=True))
        batch.add_column(sa.Column("source_provider", sa.String(length=100), nullable=True))
        batch.add_column(sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table(
        "market_prices_eod", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.add_column(sa.Column("open", sa.Numeric(precision=20, scale=4), nullable=True))
        batch.add_column(
            sa.Column("previous_close", sa.Numeric(precision=20, scale=4), nullable=True)
        )
        batch.add_column(sa.Column("volume", sa.Numeric(precision=24, scale=4), nullable=True))
        batch.add_column(sa.Column("turnover", sa.Numeric(precision=24, scale=4), nullable=True))
        batch.add_column(sa.Column("source_provider", sa.String(length=100), nullable=True))
        batch.add_column(sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column("raw_payload_id", sa.String(length=36), nullable=True))
        batch.create_foreign_key(
            "fk_market_prices_eod_raw", "data_raw_payloads", ["raw_payload_id"], ["id"]
        )
    with op.batch_alter_table(
        "quarterly_financials", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.add_column(
            sa.Column(
                "statement_type", sa.String(length=20), server_default="STANDALONE", nullable=False
            )
        )
        batch.add_column(sa.Column("period_start", sa.Date(), nullable=True))
        batch.add_column(sa.Column("period_end", sa.Date(), nullable=True))
        batch.add_column(sa.Column("source_provider", sa.String(length=100), nullable=True))
        batch.add_column(sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column("filing_id", sa.String(length=200), nullable=True))
        batch.add_column(sa.Column("raw_payload_id", sa.String(length=36), nullable=True))
        batch.add_column(sa.Column("payload_hash", sa.String(length=64), nullable=True))
        batch.add_column(sa.Column("parser_version", sa.String(length=40), nullable=True))
        batch.add_column(sa.Column("industry_metrics", sa.JSON(), nullable=True))
        batch.create_foreign_key(
            "fk_quarterly_financials_raw", "data_raw_payloads", ["raw_payload_id"], ["id"]
        )
    with op.batch_alter_table("ipos") as batch:
        batch.add_column(sa.Column("registrar", sa.String(200), nullable=True))
        batch.add_column(sa.Column("lead_managers", sa.JSON(), nullable=True))
        for name in (
            "retail_quota_pct",
            "qib_quota_pct",
            "nii_quota_pct",
            "employee_quota_pct",
            "shareholder_quota_pct",
        ):
            batch.add_column(sa.Column(name, sa.Numeric(8, 4), nullable=True))
    with op.batch_alter_table("ipo_dates") as batch:
        for name in ("anchor_date", "allotment_date", "refund_date", "demat_credit_date"):
            batch.add_column(sa.Column(name, sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    op.drop_index("ix_subscription_ipo_observed", table_name="ipo_subscriptions")
    with op.batch_alter_table("ipos") as batch:
        for name in (
            "registrar",
            "lead_managers",
            "retail_quota_pct",
            "qib_quota_pct",
            "nii_quota_pct",
            "employee_quota_pct",
            "shareholder_quota_pct",
        ):
            batch.drop_column(name)
    with op.batch_alter_table("ipo_dates") as batch:
        for name in ("anchor_date", "allotment_date", "refund_date", "demat_credit_date"):
            batch.drop_column(name)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "quarterly_financials", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_constraint("fk_quarterly_financials_raw", type_="foreignkey")
        batch.drop_column("industry_metrics")
        batch.drop_column("parser_version")
        batch.drop_column("payload_hash")
        batch.drop_column("raw_payload_id")
        batch.drop_column("filing_id")
        batch.drop_column("source_timestamp")
        batch.drop_column("source_provider")
        batch.drop_column("period_end")
        batch.drop_column("period_start")
        batch.drop_column("statement_type")
    with op.batch_alter_table(
        "market_prices_eod", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_constraint("fk_market_prices_eod_raw", type_="foreignkey")
        batch.drop_column("raw_payload_id")
        batch.drop_column("source_timestamp")
        batch.drop_column("source_provider")
        batch.drop_column("turnover")
        batch.drop_column("volume")
        batch.drop_column("previous_close")
        batch.drop_column("open")
    with op.batch_alter_table(
        "ipos", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_column("source_timestamp")
        batch.drop_column("source_provider")
        batch.drop_column("lifecycle")
        batch.drop_column("raw_status")
    with op.batch_alter_table(
        "ipo_subscriptions", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_constraint("fk_ipo_subscriptions_raw", type_="foreignkey")
        batch.drop_column("raw_payload_id")
        batch.drop_column("payload_hash")
        batch.drop_column("source_url")
        batch.drop_column("source_provider")
        batch.drop_column("categories")
    with op.batch_alter_table(
        "ipo_gmp_history", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_constraint("fk_ipo_gmp_history_raw", type_="foreignkey")
        batch.drop_column("raw_payload_id")
        batch.drop_column("source_provider")
    op.drop_index(op.f("ix_data_import_runs_job_name"), table_name="data_import_runs")
    with op.batch_alter_table(
        "data_import_runs", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_column("parameters")
        batch.drop_column("counters")
        batch.drop_column("finished_at")
        batch.drop_column("started_at")
        batch.drop_column("trigger")
        batch.drop_column("job_name")
    with op.batch_alter_table(
        "companies", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_constraint("uq_companies_isin", type_="unique")
        batch.drop_column("isin")
        batch.drop_column("company_type")
    with op.batch_alter_table(
        "annual_financials", naming_convention={"uq": "uq_%(table_name)s_%(column_0_name)s"}
    ) as batch:
        batch.drop_constraint("fk_annual_financials_raw", type_="foreignkey")
        batch.drop_constraint("uq_annual_revision", type_="unique")
        batch.drop_column("industry_metrics")
        batch.drop_column("parser_version")
        batch.drop_column("payload_hash")
        batch.drop_column("raw_payload_id")
        batch.drop_column("filing_id")
        batch.drop_column("source_timestamp")
        batch.drop_column("source_provider")
        batch.drop_column("period_end")
        batch.drop_column("period_start")
        batch.drop_column("statement_type")
        batch.drop_column("source_url")
        batch.drop_column("revision")
        batch.create_unique_constraint(
            (
                "annual_financials_company_id_financial_year_key"
                if op.get_bind().dialect.name == "postgresql"
                else "uq_annual_financials_company_id"
            ),
            ["company_id", "financial_year"],
        )
    op.drop_index(op.f("ix_ingestion_job_errors_run_id"), table_name="ingestion_job_errors")
    op.drop_table("ingestion_job_errors")
    op.drop_table("scheduler_controls")
    op.drop_table("job_locks")
    op.drop_index(op.f("ix_data_raw_payloads_payload_hash"), table_name="data_raw_payloads")
    op.drop_table("data_raw_payloads")
    # ### end Alembic commands ###
