"""normalized IPO research schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "98017c9d7309"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "advertisements",
        sa.Column("text", sa.String(length=240), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("destination_url", sa.Text(), nullable=False),
        sa.Column("placement", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_import_runs",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "data_sources",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "financial_periods",
        sa.Column("financial_year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("financial_year", "quarter"),
    )
    op.create_table(
        "future_users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "sectors",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "site_messages",
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("attribution", sa.String(length=160), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("active_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "admin_sessions",
        sa.Column("admin_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_admin_sessions_admin_id"), "admin_sessions", ["admin_id"], unique=False
    )
    op.create_index(
        op.f("ix_admin_sessions_expires_at"), "admin_sessions", ["expires_at"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("admin_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "companies",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sector_id", sa.String(length=36), nullable=True),
        sa.Column("board", sa.String(length=20), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("screener_url", sa.Text(), nullable=True),
        sa.Column("exchange_url", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sector_id"],
            ["sectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_companies_sector_id"), "companies", ["sector_id"], unique=False)
    op.create_table(
        "field_provenance",
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("field_name", sa.String(length=80), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_field_provenance_entity_id"), "field_provenance", ["entity_id"], unique=False
    )
    op.create_index(
        "ix_provenance_entity_field",
        "field_provenance",
        ["entity_type", "entity_id", "field_name"],
        unique=False,
    )
    op.create_table(
        "annual_financials",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("financial_year", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("ebitda", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("pat", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("eps", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("debt", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("cfo", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("roe", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("roce", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "financial_year"),
    )
    op.create_table(
        "business_trend_snapshots",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("score", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("methodology_version", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_business_trend_snapshots_company_id"),
        "business_trend_snapshots",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_trend_snapshots_state"),
        "business_trend_snapshots",
        ["state"],
        unique=False,
    )
    op.create_table(
        "company_identifiers",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=40), nullable=False),
        sa.Column("exchange", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "exchange"),
    )
    op.create_index(
        op.f("ix_company_identifiers_company_id"),
        "company_identifiers",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "company_price_snapshots",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("cmp", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("ath", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("high_52w", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("low_52w", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("price_date", sa.Date(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id"),
    )
    op.create_table(
        "data_quality_issues",
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_quality_issues_company_id"),
        "data_quality_issues",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "ipos",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=25), nullable=False),
        sa.Column("price_low", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("price_high", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("issue_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("listing_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=True),
        sa.Column("issue_size", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("fresh_issue", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("ofs", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("quality", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id"),
    )
    op.create_index(op.f("ix_ipos_status"), "ipos", ["status"], unique=False)
    op.create_table(
        "market_prices_eod",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("price_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "price_date"),
    )
    op.create_index(
        op.f("ix_market_prices_eod_price_date"), "market_prices_eod", ["price_date"], unique=False
    )
    op.create_table(
        "peer_companies",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("peer_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["peer_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "peer_id"),
    )
    op.create_table(
        "quarterly_financials",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("period_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column("import_key", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("ebitda", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("pat", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("eps", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("debt", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("cfo", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("roe", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("roce", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["financial_periods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "period_id", "revision"),
        sa.UniqueConstraint("import_key"),
    )
    op.create_table(
        "valuation_snapshots",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("pe", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("peer_median_pe", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("ev_ebitda", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "as_of"),
    )
    op.create_index(
        op.f("ix_valuation_snapshots_company_id"),
        "valuation_snapshots",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "future_ipo_applications",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("ipo_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["future_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "ipo_id"),
    )
    op.create_table(
        "ipo_baseline_financials",
        sa.Column("ipo_id", sa.String(length=36), nullable=False),
        sa.Column("market_cap", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("pe", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("ebitda", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("pat", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("eps", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("debt", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("cfo", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("roe", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("roce", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ipo_id"),
    )
    op.create_table(
        "ipo_dates",
        sa.Column("ipo_id", sa.String(length=36), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=True),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ipo_id"),
    )
    op.create_index(op.f("ix_ipo_dates_listing_date"), "ipo_dates", ["listing_date"], unique=False)
    op.create_table(
        "ipo_documents",
        sa.Column("ipo_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ipo_documents_ipo_id"), "ipo_documents", ["ipo_id"], unique=False)
    op.create_table(
        "ipo_gmp_history",
        sa.Column("ipo_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("import_key", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_key"),
    )
    op.create_index(op.f("ix_ipo_gmp_history_ipo_id"), "ipo_gmp_history", ["ipo_id"], unique=False)
    op.create_index(
        op.f("ix_ipo_gmp_history_observed_at"), "ipo_gmp_history", ["observed_at"], unique=False
    )
    op.create_table(
        "ipo_subscriptions",
        sa.Column("ipo_id", sa.String(length=36), nullable=False),
        sa.Column("multiple", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ipo_subscriptions_ipo_id"), "ipo_subscriptions", ["ipo_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ipo_subscriptions_ipo_id"), table_name="ipo_subscriptions")
    op.drop_table("ipo_subscriptions")
    op.drop_index(op.f("ix_ipo_gmp_history_observed_at"), table_name="ipo_gmp_history")
    op.drop_index(op.f("ix_ipo_gmp_history_ipo_id"), table_name="ipo_gmp_history")
    op.drop_table("ipo_gmp_history")
    op.drop_index(op.f("ix_ipo_documents_ipo_id"), table_name="ipo_documents")
    op.drop_table("ipo_documents")
    op.drop_index(op.f("ix_ipo_dates_listing_date"), table_name="ipo_dates")
    op.drop_table("ipo_dates")
    op.drop_table("ipo_baseline_financials")
    op.drop_table("future_ipo_applications")
    op.drop_index(op.f("ix_valuation_snapshots_company_id"), table_name="valuation_snapshots")
    op.drop_table("valuation_snapshots")
    op.drop_table("quarterly_financials")
    op.drop_table("peer_companies")
    op.drop_index(op.f("ix_market_prices_eod_price_date"), table_name="market_prices_eod")
    op.drop_table("market_prices_eod")
    op.drop_index(op.f("ix_ipos_status"), table_name="ipos")
    op.drop_table("ipos")
    op.drop_index(op.f("ix_data_quality_issues_company_id"), table_name="data_quality_issues")
    op.drop_table("data_quality_issues")
    op.drop_table("company_price_snapshots")
    op.drop_index(op.f("ix_company_identifiers_company_id"), table_name="company_identifiers")
    op.drop_table("company_identifiers")
    op.drop_index(op.f("ix_business_trend_snapshots_state"), table_name="business_trend_snapshots")
    op.drop_index(
        op.f("ix_business_trend_snapshots_company_id"), table_name="business_trend_snapshots"
    )
    op.drop_table("business_trend_snapshots")
    op.drop_table("annual_financials")
    op.drop_index("ix_provenance_entity_field", table_name="field_provenance")
    op.drop_index(op.f("ix_field_provenance_entity_id"), table_name="field_provenance")
    op.drop_table("field_provenance")
    op.drop_index(op.f("ix_companies_sector_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_admin_sessions_expires_at"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_admin_id"), table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_table("site_messages")
    op.drop_table("sectors")
    op.drop_table("future_users")
    op.drop_table("financial_periods")
    op.drop_table("data_sources")
    op.drop_table("data_import_runs")
    op.drop_table("advertisements")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
