'use client';
import {useRecordTools} from './webmcp';
import {useState,useEffect} from 'react';
import {NativeSelect} from '@/components/ui/native-select';
import {companies} from '@/lib/data';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
export default function AdminForm(){useRecordTools();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [records,setRecords]=useState<{id:string;company_id:string;kind:string;updated_at:string}[]>([]);async function load(){try{const r=await fetch('/api/admin');const data=await r.json() as {error?:string;records:typeof records};if(!r.ok)throw Error(data.error);setRecords(data.records)}catch(e){setMessage(e instanceof Error?e.message:'Unable to load records')}}useEffect(()=>{void load()},[]);async function submit(event:React.FormEvent<HTMLFormElement>,kind:string){event.preventDefault();setBusy(true);setMessage('');const f=new FormData(event.currentTarget);const body:Record<string,unknown>={kind};for(const [key,val] of f.entries())body[key]=['companyId','sourceUrl','period'].includes(key)?String(val):Number(val);try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json() as {error?:string};if(!r.ok)throw Error(result.error);await load();setMessage('Saved. The company record is updated.')}catch(e){setMessage(e instanceof Error?e.message:'Save failed. Please retry.')}finally{setBusy(false)}}return <><div className="panel"><p>Sample-company maintenance. Changes are saved centrally and appear on the public research pages. Saving an existing quarter replaces that quarter’s figures.</p><Tabs defaultValue="gmp"><TabsList><TabsTrigger value="gmp">GMP update</TabsTrigger><TabsTrigger value="quarter">Quarterly result</TabsTrigger></TabsList>{['gmp','quarter'].map(kind=><TabsContent value={kind} key={kind}><form className="form-grid" onSubmit={e=>submit(e,kind)}><label>Company<NativeSelect name="companyId" required>{companies.filter(c=>kind==='quarter'||c.status!=='Listed').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</NativeSelect></label>{kind==='gmp'?<label>GMP (₹)<input name="gmp" type="number" step="0.01" required/></label>:<><label>Quarter<input name="period" placeholder="Q1 FY27" pattern="Q[1-4] FY[0-9]{2}" required/></label>{[['revenue','Revenue (₹ Cr)'],['ebitda','EBITDA (₹ Cr)'],['pat','PAT (₹ Cr)'],['eps','EPS (₹)'],['debt','Debt (₹ Cr)'],['cashFlow','Operating cash flow (₹ Cr)']].map(([name,label])=><label key={name}>{label}<input name={name} type="number" step="0.01" min={['revenue','debt'].includes(name)?0:undefined} required/></label>)}</>}<label className="full">Source URL<input name="sourceUrl" type="url" placeholder="https://…" required/></label><div className="full"><button className="primary-button" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form></TabsContent>)}</Tabs><p role="status" aria-live="polite">{message}</p></div><section className="panel"><h2>Recently maintained</h2>{records.length?records.map(r=><p key={r.id}>{companies.find(c=>c.id===r.company_id)?.name} · {r.kind} · {new Date(r.updated_at).toLocaleString()}</p>):<p>No saved updates yet.</p>}</section></>}


