import {env} from 'cloudflare:workers';
import {isAdmin} from '@/lib/admin';
import {getRecords} from '@/lib/providers';
import {companies} from '@/lib/data';
import {z} from 'zod';
const number=z.number().finite();
const schema=z.object({companyId:z.enum(companies.map(c=>c.id) as [string,...string[]]),sourceUrl:z.string().url().refine(v=>new URL(v).protocol==='https:'),kind:z.enum(['gmp','quarter']),gmp:number.optional(),period:z.string().regex(/^Q[1-4] FY\d{2}$/).optional(),revenue:number.nonnegative().optional(),ebitda:number.optional(),pat:number.optional(),eps:number.optional(),debt:number.nonnegative().optional(),cashFlow:number.optional()});
export async function GET(){if(!await isAdmin())return Response.json({error:'Access denied'},{status:403});try{return Response.json({records:await getRecords()})}catch{return Response.json({error:'Records are unavailable. Please try again.'},{status:503})}}
export async function POST(request:Request){const user=await isAdmin();if(!user)return Response.json({error:'Access denied'},{status:403});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid request origin'},{status:403});let data;try{data=schema.parse(await request.json());if(data.kind==='gmp'&&data.gmp===undefined)throw Error();if(data.kind==='quarter'&&[data.period,data.revenue,data.ebitda,data.pat,data.eps,data.debt,data.cashFlow].some(x=>x===undefined))throw Error()}catch{return Response.json({error:'Check the company, source URL and all required figures.'},{status:400})}try{if(!env.DB)throw Error();const id=`${data.companyId}:${data.kind}:${data.period??'latest'}`;await env.DB.prepare('INSERT INTO records (id,kind,company_id,payload,source_url,updated_at,updated_by) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,source_url=excluded.source_url,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind(id,data.kind,data.companyId,JSON.stringify(data),data.sourceUrl,new Date().toISOString(),user.email).run();return Response.json({saved:true})}catch{return Response.json({error:'Could not save. Your entries are preserved; please retry.'},{status:503})}}
